### ISSUE TITLE
Link Created Equinix VLANs to Harvester VLANs

### ISSUE THREAD

**Issue by jmcglock** [rancherlabs/harvester-equinix-terraform#37]
It would be nice if the VLANs that are created in Equinix while spinning this cluster up, could be linked inside of Harvester as VM networks automatically.

For example:
VLAN 1000 in Equinix -> VM-Network-1000 in Harvester

**Comment by dnoland1** [comment]
Yes, we have an issue for this already - https://github.com/rancherlabs/harvester-equinix-terraform/issues/9

Will close this one as a duplicate.
