### ISSUE TITLE
Worker Nodes Cannot Join Cluster Until Control Node is Up

### ISSUE THREAD

**Issue by jmcglock** [rancherlabs/harvester-equinix-terraform#38]
One solution that I have been doing to get around this is to: 

1. power off all the machines after the initial Harvester installation is complete
2. power on the master/control node and wait for the cluster to become ready
3. power on the worker nodes so they can join the cluster

Is there a way to do this automatically?

**Comment by dnoland1** [comment]
Workers should automatically retry joining the cluster without having to power anything off. If not, this is probably an issue with the product itself and not related to the terraform.

**Comment by jmcglock** [comment]
I'll consider this answered. Thanks for the quick response.
